server:
    port: 8082

management:
    security:
        enabled: false
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        name: microservice-consumer-movie

eureka:
    client:
        service-url:
            defaultZone: http://user:p123456@localhost:8761/eureka/
    instance:
        prefer-ip-address: true
ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true




