server:
    port: 8082

management:
    security:
        enabled: false
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        name: microservice-consumer-movie
    main:
        allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#   zipkin:
#    base-url: http://zipkin-server/
    sleuth:
        sampler:
          percentage: 1.0
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    zipkin:
      rabbitmq:
        queue: zipkin

eureka:
    client:
        service-url:
            defaultZone: http://user:p123456@localhost:8761/eureka/
    instance:
        prefer-ip-address: true
ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true

logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.springframeword.web.servlet.DispatcherServlet: DEBUG




