server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://user:p123456@localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  security:
    user:
      name: user
      password: p123456

